name: image-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::jupyterlab
  - pandas
  - Pillow
  - tensorflow
  - scikit-learn
  - matplotlib
  - conda-forge::seaborn
  - conda-forge::imbalanced-learn